resources:
- ../common
- 03-sonataflow_platform.yaml
- 04-cluster-platform.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: postgres-secrets
    literals:
      - POSTGRES_USER=sonataflow
      - POSTGRES_PASSWORD=sonataflow
      - POSTGRES_DB=sonataflow
      - PGDATA=/var/lib/postgresql/data/mydata

sortOptions:
  order: fifo