apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  # DI has individual broker configuration
  # JS has individual broker configuration
  # WF has no Broker configuration, the WF deployment will fail.
  services:
    dataIndex:
      enabled: true
      source:
        ref:
          name: sonataflow-broker
          apiVersion: eventing.knative.dev/v1
          kind: Broker
      persistence:
        postgresql:
          serviceRef:
            name: postgres
            databaseName: sonataflow
            databaseSchema: data-index-schema
          secretRef:
            name: postgres-secrets
            userKey: POSTGRES_USER
            passwordKey: POSTGRES_PASSWORD
      podTemplate:
        initContainers:
          - name: init-postgres
            image: registry.access.redhat.com/ubi9/ubi-minimal:latest
            imagePullPolicy: IfNotPresent
            command: [ 'sh', '-c', 'until (echo 1 > /dev/tcp/postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/5432) >/dev/null 2>&1; do echo "Waiting for postgres server"; sleep 3; done;' ]
    jobService:
      enabled: true
      source:
        ref:
          name: sonataflow-broker
          apiVersion: eventing.knative.dev/v1
          kind: Broker
      sink:
        ref:
          name: sonataflow-broker
          apiVersion: eventing.knative.dev/v1
          kind: Broker
      persistence:
        postgresql:
          serviceRef:
            name: postgres
            databaseName: sonataflow
            databaseSchema: jobs-service-schema
          secretRef:
            name: postgres-secrets
            userKey: POSTGRES_USER
            passwordKey: POSTGRES_PASSWORD
      podTemplate:
        initContainers:
                - name: init-postgres
                  image: registry.access.redhat.com/ubi9/ubi-minimal:latest
                  imagePullPolicy: IfNotPresent
                  command: [ 'sh', '-c', 'until (echo 1 > /dev/tcp/postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/5432) >/dev/null 2>&1; do echo "Waiting for postgres server"; sleep 3; done;' ]
