apiVersion: v1
data:
  application.properties: |   
    # Kogito runtime persistence configurations
    kogito.persistence.query.timeout.millis=10000
    # Set to false to create the tables manually. Automatic generation is a different use case.
    quarkus.flyway.migrate-at-start=true
    # REMOVE
    quarkus.swagger-ui.always-include=true
kind: ConfigMap
metadata:
  labels:
    app: callbackstatetimeouts
  name: callbackstatetimeouts-props
