---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: sonataflow-psql-postgresql
  name: sonataflow-psql-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sonataflow-psql-postgresql
  name: sonataflow-psql-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonataflow-psql-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonataflow-psql-postgresql
    spec:
      imagePullSecrets:
        - name: 6340056-sonataflow-testing-pull-secret
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-13:1-173
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /var/lib/pgsql/data
          envFrom:
            - secretRef:
                name: sonataflow-psql-postgresql
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: sonataflow-psql-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sonataflow-psql-postgresql
  name: sonataflow-psql-postgresql
spec:
  selector:
    app.kubernetes.io/name: sonataflow-psql-postgresql
  ports:
    - port: 5432
