apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-fail
    helm.sh/hook-weight: "2"
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: sonataflow-infra
