apiVersion: v1
data:
  application.properties: |
    # Data Index configuration
    mp.messaging.outgoing.kogito-processdefinitions-events.url=http://data-index-service-postgresql/definitions

    mp.messaging.outgoing.kogito-processinstances-events.url=http://data-index-service-postgresql/processes

    mp.messaging.outgoing.kogito-usertaskinstances-events.url=http://data-index-service-postgresql/tasks
        
    kogito.events.processdefinitions.enabled=true
    kogito.events.processinstances.enabled=true
  
    # Skip user tasks events sending.
    kogito.events.usertasks.enabled=false
  
    quarkus.log.category."io.smallrye.reactive.messaging".level = DEBUG
    quarkus.log.category."org.kie".level = DEBUG
    quarkus.log.category."io.quarkus.reactivemessaging".level = DEBUG
    quarkus.log.category."io.vertx".level = DEBUG
kind: ConfigMap
metadata:
  labels:
    app: helloworld
  name: helloworld-props
