resources:
- ../../platforms/dataindex_and_jobservice_platform
- ../../workflows/sonataflow-greeting
- ../../workflows/sonataflow-callbackstatetimeouts
- ../../workflows/sonataflow-workflowtimeouts

sortOptions:
  order: fifo
