resources:
- ../../platforms/dataindex_and_jobservice_platform
- ../../infra/service_discovery
- ../../workflows/sonataflow-greeting
- ../../workflows/sonataflow-callbackstatetimeouts
- ../../workflows/sonataflow-workflowtimeouts
