resources:
- 01-postgres.yaml
- 02-dataindex.yaml

secretGenerator:
  - name: postgres-secrets
    literals:
      - POSTGRESQL_USER=sonataflow
      - POSTGRESQL_PASSWORD=sonataflow
      - POSTGRESQL_DATABASE=sonataflow
      - PGDATA=/var/lib/pgsql/data/userdata

configMapGenerator:
  - name: dataindex-properties
    files:
      - application.properties

