resources:
- 05-configmap_callbackstatetimeouts-props.yaml
- 06-sonataflow_callbackstatetimeouts.sw.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: postgres-secrets
    literals:
      - POSTGRES_USER=sonataflow
      - POSTGRES_PASSWORD=sonataflow

sortOptions:
  order: fifo