apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: workflowtimeouts
  annotations:
    sonataflow.org/description: Workflow Timeouts Example k8s
    sonataflow.org/version: 0.0.1
spec:
  # Persistence is defined, and thus, this configuration must be applied independently of the SFP persistence configuration.
  persistence:
    postgresql:
      secretRef:
        name: postgres-secrets
        userKey: POSTGRESQL_USER
        passwordKey: POSTGRESQL_PASSWORD
      serviceRef:
        name: postgres
        # use the same DB for simplicity
        databaseName: sonataflow_pfdb
        # setting schema name here intentionally, if not set, the WF name will be used instead.
        databaseSchema: wf_timeouts
  flow:
    start: PrintStartMessage
    timeouts:
      workflowExecTimeout:
        duration: 'PT30S'
    events:
      - name: wakeUpEvent
        source: ''
        type: wake_up_event_type
    functions:
      - name: systemOut
        type: custom
        operation: sysout
    states:
      - name: PrintStartMessage
        type: operation
        actions:
          - name: printSystemOut
            functionRef:
              refName: systemOut
              arguments:
                message: "${\"workflow-timeouts: \" + $WORKFLOW.instanceId + \" has started.\"}"
        transition: WaitForEvent
      - name: WaitForEvent
        type: event
        onEvents:
          - eventRefs: [ wakeUpEvent ]
            actions:
              - name: printAfterWakeUpEvent
                functionRef:
                  refName: systemOut
                  arguments:
                    message: "${\"workflow-timeouts: \" + $WORKFLOW.instanceId + \" executing actions for wake_up_event.\"}"
        end: true