apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: workflowtimeouts
  annotations:
    sonataflow.org/description: Workflow Timeouts Example k8s
    sonataflow.org/version: 0.0.1
spec:
  # Persistence is defined, and thus, this configuration must be applied independently of the SFP persistence configuration.
  persistence:
    postgresql:
      secretRef:
        name: postgres-secrets
        userKey: POSTGRESQL_USER
        passwordKey: POSTGRESQL_PASSWORD
      serviceRef:
        name: postgres
        # use the same DB for simplicity
        databaseName: sonataflow
        # setting schema name here intentionally to test, if not set, the WF name will be used instead.
        databaseSchema: wf_timeouts
  podTemplate:
    container:
      env:
        # By now, to align with kogito-runtimes default configurations the schema initialization is disabled by default.
        # As example, we can configure that value as an env var in the WF container.
        - name: QUARKUS_FLYWAY_MIGRATE_AT_START
          value: 'true'
  flow:
    start: PrintStartMessage
    timeouts:
      workflowExecTimeout:
        duration: 'PT30S'
    events:
      - name: wakeUpEvent
        source: ''
        type: wake_up_event_type
    functions:
      - name: systemOut
        type: custom
        operation: sysout
    states:
      - name: PrintStartMessage
        type: operation
        actions:
          - name: printSystemOut
            functionRef:
              refName: systemOut
              arguments:
                message: "${\"workflow-timeouts: \" + $WORKFLOW.instanceId + \" has started.\"}"
        transition: WaitForEvent
      - name: WaitForEvent
        type: event
        onEvents:
          - eventRefs: [ wakeUpEvent ]
            actions:
              - name: printAfterWakeUpEvent
                functionRef:
                  refName: systemOut
                  arguments:
                    message: "${\"workflow-timeouts: \" + $WORKFLOW.instanceId + \" executing actions for wake_up_event.\"}"
        end: true