apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: helloworld
  annotations:
    sonataflow.org/description: Hello World Workflow
    sonataflow.org/version: 0.0.1
spec:
  # Empty persistence ignores the SPF persistence configuration, no matter if set or not, this WF won't use persistence.
  persistence: {}
  flow:
    start: Inject Hello World
    states:
      - name: Inject Hello World
        type: inject
        data:
          greeting: Hello World
        transition: Inject Mantra
      - name: Inject Mantra
        type: inject
        data:
          mantra: Serverless Workflow is awesome!
        end: true