resources:
- 6340056-sonataflow-testing-pull-secret.yaml
- 01-postgres.yaml
- 02-sonataflow_platform.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: postgres-secrets
    literals:
      - POSTGRESQL_USER=sonataflow
      - POSTGRESQL_PASSWORD=sonataflow
      - POSTGRESQL_DATABASE=sonataflow
      - PGDATA=/var/lib/pgsql/data/userdata

sortOptions:
  order: fifo

